version: 2.1
jobs:
  build:
    docker:
      - image: php:8.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Deploy to cPanel
          command: |
            sshpass -p $ftp_password ssh -o StrictHostKeyChecking=no $ftp_username@109.106.253.149 "cd /home/$ftp_username/public_html/cms; git pull"