version: 2.1
jobs:
  build:
    docker:
      - image: php:8.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            - v1-dependencies-

      - run:
          name: Install Composer
          command: |
            apt-get update
            apt-get install -y unzip
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer

      - run:
          name: Install Dependencies
          command: composer install 

      - run:
          name: Update Dependencies
          command: composer update 

      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-{{ checksum "composer.lock" }}

      - run:
          name: Generate Application Key
          command: php artisan key:generate

      - run:
          name: Run Database Migrations
          command: php artisan migrate --force

      - run:
          name: Run Tests
          command: vendor/bin/phpunit