version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-{{ checksum "composer.lock" }}

      - run:
          name: Generate Application Key
          command: php artisan key:generate

      - run:
          name: Run Database Migrations
          command: php artisan migrate --force

      - run:
          name: Run Tests
          command: vendor/bin/phpunit