version: 2.1
jobs:
  build:
    docker:
      - image: php:8.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Deploy to cPanel
          command: |
            apt-get update
            apt-get -y install lftp
            lftp -c "set ftp:ssl-allow no; open -u $ftp_usename,$ftp_password www.desagetasan.id; mirror -Rnev . /home/$ftp_username/public_html/cms"